CREATE TABLE PLANO_ASSINATURA (
	PLANO_ASSINATURA_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_PLANO_ASSINATURA_ID PRIMARY KEY,
	NOME_PLANO VARCHAR(100) NOT NULL CONSTRAINT UN_PLANO_ASSINATURA_NOME_PLANO UNIQUE,
	PRECO DECIMAL (10, 2) NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_PRECO CHECK (PRECO > 0),
	RESOLUCAO_MAX VARCHAR(20) NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_RESOLUCAO_MAX CHECK (RESOLUCAO_MAX IN ('HD', 'FULL HD', '4K')),
	QTD_DISPOSITIVOS INT NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_QTD_DISPOSITIVOS CHECK (QTD_DISPOSITIVOS > 0)
); GO

CREATE TABLE USUARIO (
	USUARIO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_USUARIO_ID PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR (150) NOT NULL,
	SENHA VARCHAR(255) NOT NULL CONSTRAINT CK_USUARIO_SENHA CHECK (LEN(SENHA) >= 8),
	DATA_CADASTRO DATETIME NOT NULL,
	PLANO_ASSINATURA_ID INT NOT NULL CONSTRAINT FK_USUARIO_PLANO_ASSINATURA_ID FOREIGN KEY REFERENCES PLANO_ASSINATURA(PLANO_ASSINATURA_ID)
); GO

SELECT * FROM PLANO_ASSINATURA, USUARIO;