CREATE TABLE PLANO_ASSINATURA (
	PLANO_ASSINATURA_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_PLANO_ASSINATURA_ID PRIMARY KEY,
	NOME_PLANO VARCHAR(100) NOT NULL CONSTRAINT UN_PLANO_ASSINATURA_NOME_PLANO UNIQUE,
	PRECO DECIMAL (10, 2) NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_PRECO CHECK (PRECO > 0),
	RESOLUCAO_MAX VARCHAR(20) NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_RESOLUCAO_MAX CHECK (RESOLUCAO_MAX IN ('HD', 'FULL HD', '4K')),
	QTD_DISPOSITIVOS INT NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_QTD_DISPOSITIVOS CHECK (QTD_DISPOSITIVOS > 0)
);

CREATE TABLE USUARIO (
	USUARIO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_USUARIO_ID PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR (150) NOT NULL,
	SENHA VARCHAR(255) NOT NULL CONSTRAINT CK_USUARIO_SENHA CHECK (LEN(SENHA) >= 8),
	DATA_CADASTRO DATETIME NOT NULL,
	PLANO_ASSINATURA_ID INT NOT NULL CONSTRAINT FK_USUARIO_PLANO_ASSINATURA_ID FOREIGN KEY REFERENCES PLANO_ASSINATURA(PLANO_ASSINATURA_ID)
);

CREATE TABLE FILME (
	
	FILME_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_FILME_ID PRIMARY KEY,
	TITULO VARCHAR(255) NOT NULL CONSTRAINT CK_FILME_TITULO CHECK (LEN(TITULO) >= 2),
	DURACAO INT NOT NULL CONSTRAINT CK_FILME_DURACAO CHECK (DURACAO > 0),
	ANO_LANCAMENTO INT NOT NULL,
	CLASSIFICACAO VARCHAR(10) NOT NULL CONSTRAINT CK_FILME_CLASSIFICACAO CHECK (CLASSIFICACAO IN ('L', '10+', '12+', '14+', '16+', '18+'))
); 

CREATE TABLE GENERO (
	GENERO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_GENREO_ID PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL CONSTRAINT UN_GENERO_NOME UNIQUE
); 

CREATE TABLE FILME_PLANO_ASSINATURA (
	FILME_PLANO_ASSINATURA_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_FILME_PLANO_ASSINATURA_ID PRIMARY KEY,
	FILME_ID INT NOT NULL CONSTRAINT FK_FILME_PLANO_ASSINATURA_FILME_ID FOREIGN KEY REFERENCES FILME ( FILME_ID ),
	PLANO_ASSINATURA_ID INT NOT NULL CONSTRAINT FK_FILME_PLANO_ASSINATURA_PLANO_ASSINATURA_ID FOREIGN KEY REFERENCES PLANO_ASSINATURA( PLANO_ASSINATURA_ID )
); 

CREATE TABLE FILME_GENERO (
	FILME_GENERO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_FILME_GENERO_ID PRIMARY KEY,
	FILME_ID INT NOT NULL CONSTRAINT FK_FILME_GENERO_FILME_ID FOREIGN KEY REFERENCES FILME ( FILME_ID ),
	GENERO_ID INT NOT NULL CONSTRAINT FK_FILME_GENERO_GENERO_ID FOREIGN KEY REFERENCES GENERO( GENERO_ID )
); 

CREATE TABLE VISUALIZACAO (
	VISUALIZACAO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_VISUALIZACAO_ID PRIMARY KEY,
	USUARIO_ID INT NOT NULL CONSTRAINT FK_VISUALIZACAO_USUARIO_ID FOREIGN KEY REFERENCES USUARIO ( USUARIO_ID ),
	FILME_ID INT NOT NULL CONSTRAINT FK_VISUALIZACAO_FILME_ID FOREIGN KEY REFERENCES FILME ( FILME_ID ),
	DATA_HORA DATETIME NOT NULL,
	TEMPO_ASSISTIDO INT NOT NULL CONSTRAINT CK_VISUALIZACAO_TEMPO_ASSISTIDO CHECK (TEMPO_ASSISTIDO >= 0)
); 

CREATE TABLE AVALIACAO (
	AVALIACAO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_AVALIACAO_ID PRIMARY KEY,
	USUARIO_ID INT NOT NULL CONSTRAINT FK_AVALIACAO_USUARIO_ID FOREIGN KEY REFERENCES USUARIO ( USUARIO_ID ),
	FILME_ID INT NOT NULL CONSTRAINT FK_AVALIACAO_FILME_ID FOREIGN KEY REFERENCES FILME ( FILME_ID ),
	VISUALIZACAO_ID INT CONSTRAINT FK_AVALIACAO_VISUALIZACAO_ID FOREIGN KEY REFERENCES VISUALIZACAO ( VISUALIZACAO_ID ),
	NOTA DECIMAL(2,1) NOT NULL  CONSTRAINT CK_AVALIACAO_NOTA CHECK (NOTA BETWEEN 0.0 AND 5.0),
	COMENTARIO VARCHAR(500)
); 

SELECT * FROM PLANO_ASSINATURA, USUARIO, FILME, GENERO, FILME_PLANO_ASSINATURA, FILME_GENERO, VISUALIZACAO, AVALIACAO;