--Etapa 1 – Criação das Tabelas (3 pontos)
CREATE TABLE ALUNO (
	ALUNO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ALUNOS PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR (150) NOT NULL UNIQUE,
	DATA_NASCIMENTO DATETIME NOT NULL,
);	

CREATE TABLE CURSO (
    CURSO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_CURSOS PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL CONSTRAINT UN_NOME UNIQUE,
    CARGA_HORARIA INT NOT NULL CONSTRAINT CK_CURSO_CARGA_HORARIA CHECK (CARGA_HORARIA >= 0),
    NIVEL VARCHAR(20) NOT NULL CONSTRAINT CK_CURSO_NIVEL CHECK (NIVEL IN ('Básico', 'Intermediário', 'Avançado'))
);

CREATE TABLE MATRICULA(
	MATRICULA_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_MATRICULA PRIMARY KEY,
	ALUNO_ID INT NOT NULL CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY REFERENCES ALUNO(ALUNO_ID),
	CURSO_ID INT NOT NULL CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY REFERENCES CURSO(CURSO_ID),
	DATA_MATRICULA DATETIME NOT NULL,
); 

--Etapa 2 – Inserção de Dados (2 pontos)
INSERT INTO ALUNO (NOME, EMAIL, DATA_NASCIMENTO)
VALUES ('Leo', 'Leo@gmail.com', '2005-04-12'),
('Jeferson', 'Jeferson@gmail.com', '2006-04-12'),
('Robson', 'Robson@gmail.com', '2002-04-12'),
('Marta', 'Marta@gmail.com', '2012-04-12'),
('Cleo', 'Cleo@gmail.com', '2015-04-12');

INSERT INTO CURSO (NOME, CARGA_HORARIA, NIVEL)
VALUES ('CALC', '20', 'Básico'),
('MAT', '45', 'Avançado'),
('ED', '20', 'Básico'),
('FIS', '25', 'Intermediário'),
('QUIM', '15', 'Intermediário'),
('PT', '55', 'Avançado');

INSERT INTO MATRICULA (ALUNO_ID, CURSO_ID, DATA_MATRICULA)
VALUES ('3', '1', '2025-09-09T23:30:00'),
('3', '1', '2025-09-16T18:30:00'),
('2', '4', '2025-09-17T21:15:00'),
('4', '3', '2025-09-14T19:45:00'),
('5', '2', '2025-09-13T22:00:00'),
('4', '1', '2025-09-12T17:20:00'),
('5', '1', '2025-09-11T20:10:00'),
('5', '3', '2025-09-10T16:00:00');

--Etapa 3 – Atualizações (1 ponto)
UPDATE ALUNO
SET NOME = 'Robson',
    EMAIL = 'robson@email.com'
WHERE ALUNO_ID = 1;

UPDATE CURSO
SET NIVEL = 'Intermediário'
WHERE NIVEL = 'Básico';

UPDATE CURSO
SET CARGA_HORARIA = '10'
WHERE CURSO_ID = 3;

--Etapa 4 – Remoções (1 ponto)
DELETE FROM MATRICULA
WHERE ALUNO_ID = 3 AND CURSO_ID = 1;

DELETE FROM MATRICULA
WHERE CURSO_ID = 1;
DELETE FROM CURSO
WHERE CURSO_ID = 1;

--Etapa 5 – Consultas (3 pontos)
SELECT NOME, EMAIL FROM ALUNO;

SELECT NOME, CARGA_HORARIA FROM CURSO;
SELECT * FROM CURSO WHERE CARGA_HORARIA > 40;

SELECT ALUNO.NOME AS NOME_ALUNO, CURSO.NOME AS NOME_CURSO FROM MATRICULA
JOIN ALUNO ON MATRICULA.ALUNO_ID = ALUNO.ALUNO_ID
JOIN CURSO ON MATRICULA.CURSO_ID = CURSO.CURSO_ID;

SELECT ALUNO.NOME, CURSO.NOME FROM MATRICULA
JOIN ALUNO ON MATRICULA.ALUNO_ID = ALUNO.ALUNO_ID
JOIN CURSO ON MATRICULA.CURSO_ID = CURSO.CURSO_ID;

SELECT ALUNO.NOME, CURSO.NOME FROM MATRICULA
JOIN ALUNO ON MATRICULA.ALUNO_ID = ALUNO.ALUNO_ID
JOIN CURSO ON MATRICULA.CURSO_ID = CURSO.CURSO_ID;

SELECT ALUNO.NOME, ALUNO.EMAIL FROM ALUNO
LEFT JOIN MATRICULA ON ALUNO.ALUNO_ID = MATRICULA.ALUNO_ID
WHERE MATRICULA.ALUNO_ID IS NULL;