CREATE TABLE ALUNOS (
	ALUNO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ALUNOS PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL CONSTRAINT CK_ALUNOS_NOME CHECK (LEN(NOME) >= 5),
	IDADE INT NOT NULL CONSTRAINT CK_ALUNOS_IDADE CHECK (IDADE >= 18)
); GO

CREATE TABLE CURSOS (
	CURSO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_CURSOS PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL UNIQUE,
); GO

--CREATE TABLE CURSOS (
--	CURSO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_CURSOS PRIMARY KEY,
--	NOME VARCHAR(100) NOT NULL CONSTRAINT UN_CURSOS_NOME UNIQUE,
--); GO

CREATE TABLE ALUNO_CURSO(
	ALUNO_CURSO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ALUNO_CURSO PRIMARY KEY,
	ALUNO_ID INT NOT NULL CONSTRAINT FK_ALUNO FOREIGN KEY REFERENCES ALUNOS(ALUNO_ID),
	CURSO_ID INT NOT NULL CONSTRAINT FK_CURSO FOREIGN KEY REFERENCES CURSOS(CURSO_ID),
); GO

-- INSERÇÃO DE DADOS
INSERT INTO ALUNOS (NOME, IDADE) VALUES ('CARLOS SILVA', 22);
INSERT INTO ALUNOS (NOME, IDADE) VALUES ('ANA SOUZA', 19);

INSERT INTO CURSOS (NOME) VALUES ('BANCO DE DADOS');
INSERT INTO CURSOS (NOME) VALUES ('DESENVOLVIMENTO WEB');

-- CONSULTA
SELECT * FROM ALUNOS;
SELECT * FROM CURSOS;
SELECT * FROM ALUNO_CURSO;

-- ASSOCIA O ALUNO CARLOS SILVA (ID: 1) COM O CURSO DE BD (ID: 1)
INSERT INTO ALUNO_CURSO (ALUNO_ID, CURSO_ID) VALUES (1, 1);
INSERT INTO ALUNO_CURSO (ALUNO_ID, CURSO_ID) VALUES (1, 2);
INSERT INTO ALUNO_CURSO (ALUNO_ID, CURSO_ID) VALUES (2, 1);

SELECT
	ALUNOS.NOME AS ALUNO,
	CURSOS.NOME AS CURSO
FROM
	ALUNO_CURSO
JOIN
	ALUNOS ON ALUNO_CURSO.ALUNO_ID = ALUNOS.ALUNO_ID
JOIN
	CURSOS ON ALUNO_CURSO.CURSO_ID = CURSOS.CURSO_ID;