CREATE TABLE PLANO_ASSINATURA (
	PLANO_ASSINATURA_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_PLANO_ASSINATURA PRIMARY KEY,
	NOME_PLANO VARCHAR(100) NOT NULL CONSTRAINT UN_PLANO_ASSINATURA_NOME_PLANO UNIQUE,
	PRECO DECIMAL (10, 2) NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_PRECO CHECK (PRECO > 0),
	RESOLUCAO_MAX VARCHAR(20) NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_RESOLUCAO_MAX CHECK (RESOLUCAO_MAX IN ('HD', 'FULL HD', '4K')),
	QTD_DISPOSITIVOS INT NOT NULL CONSTRAINT CK_PLANO_ASSINATURA_QTD_DISPOSITIVOS CHECK (QTD_DISPOSITIVOS > 0)
);

CREATE TABLE USUARIO (
	USUARIO_ID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_USUARIO PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR (150) NOT NULL,
	SENHA VARCHAR(255) NOT NULL CONSTRAINT CK_USUARIO_SENHA CHECK (LEN(SENHA) >= 8),
	DATA_CADASTRO DATETIME NOT NULL,
	PLANO_ASSINATURA_ID INT NOT NULL CONSTRAINT FK_USUARIO_PLANO_ASSINATURA FOREIGN KEY REFERENCES PLANO_ASSINATURA(PLANO_ASSINATURA_ID)
);

CREATE TABLE FILME (
	FILME_ID INT IDENTITY(1, 1) CONSTRAINT PK_FILME PRIMARY KEY,
	TITULO VARCHAR(255) NOT NULL CONSTRAINT CK_FILME_TITULO CHECK(LEN(TITULO) >= 2),
	DURACAO INT NOT NULL CONSTRAINT CK_FILME_DURACAO CHECK(DURACAO > 0),
	ANO_LANCAMENTO INT NOT NULL ,
	CLASSIFICACAO VARCHAR(10) NOT NULL CONSTRAINT CK_FILME_CLASSIFICACAO CHECK (CLASSIFICACAO IN ('L', '10+', '12+', '14+', '16+', '18+'))
);
 
CREATE TABLE GENERO (
	GENERO_ID INT IDENTITY(1, 1) CONSTRAINT PK_GENERO PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL CONSTRAINT UN_GENERO_NOME UNIQUE
);
 
CREATE TABLE FILME_PLANO_ASSINATURA (
	FILME_PLANO_ASSINATURA_ID INT IDENTITY(1, 1) CONSTRAINT PK_FILME_PLANO_ASSINATURA PRIMARY KEY,
	FILME_ID INT NOT NULL CONSTRAINT FK_FILME_PLANO_ASSINATURA_FILME FOREIGN KEY REFERENCES FILME (FILME_ID),
	PLANO_ASSINATURA_ID INT NOT NULL CONSTRAINT FK_FILME_PLANO_ASSINATURA_PLANO_ASSINATURA FOREIGN KEY REFERENCES PLANO_ASSINATURA (PLANO_ASSINATURA_ID)
);
 
 
CREATE TABLE FILME_GENERO (
	FILME_GENERO_ID INT IDENTITY(1, 1) CONSTRAINT PK_FILME_GENERO PRIMARY KEY,
	FILME_ID INT NOT NULL CONSTRAINT FK_FILME_GENERO_FILME FOREIGN KEY REFERENCES FILME (FILME_ID),
	GENERO_ID INT NOT NULL CONSTRAINT FK_FILME_GENERO_GENERO FOREIGN KEY REFERENCES GENERO (GENERO_ID)
);

CREATE TABLE VISUALIZACAO (
	VISUALIZACAO_ID INT IDENTITY(1, 1) CONSTRAINT PK_VISUALIZACAO PRIMARY KEY,
	USUARIO_ID INT NOT NULL CONSTRAINT FK_VISUALIZACAO_USUARIO FOREIGN KEY REFERENCES USUARIO (USUARIO_ID),
	FILME_ID INT NOT NULL CONSTRAINT FK_VISUALIZACAO_FILME FOREIGN KEY REFERENCES FILME (FILME_ID),
	DATA_HORA DATETIME NOT NULL,
	TEMPO_ASSISTIDO INT NOT NULL CONSTRAINT CK_VISUALIZACAO_TEMPO_ASSISTIDO CHECK (TEMPO_ASSISTIDO >= 0)
);
 
CREATE TABLE AVALIACAO (
	AVALIACAO_ID INT IDENTITY(1, 1) CONSTRAINT PK_AVALIACAO PRIMARY KEY,
	USUARIO_ID INT NOT NULL CONSTRAINT FK_AVALIACAO_USUARIO FOREIGN KEY REFERENCES USUARIO (USUARIO_ID),
	FILME_ID INT NOT NULL CONSTRAINT FK_AVALIACAO_FILME FOREIGN KEY REFERENCES FILME (FILME_ID),
	VISUALIZACAO_ID INT NOT NULL CONSTRAINT FK_AVALIACAO_VISUALIZACAO FOREIGN KEY REFERENCES VISUALIZACAO (VISUALIZACAO_ID),
	NOTA DECIMAL(2, 1) NOT NULL CONSTRAINT CK_AVALIACAO_NOTA CHECK (NOTA BETWEEN 0.0 AND 5.0),
	COMENTARIO VARCHAR(500)
);

DROP TABLE AVALIACAO;
DROP TABLE VISUALIZACAO;
DROP TABLE FILME_GENERO;
DROP TABLE FILME_PLANO_ASSINATURA;
DROP TABLE GENERO;
DROP TABLE FILME;
DROP TABLE USUARIO;
DROP TABLE PLANO_ASSINATURA;
